# Generated by Django 4.2.8 on 2023-12-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to='app.family')),
                ('father_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father', to='app.node')),
                ('mother_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother', to='app.node')),
            ],
        ),
        migrations.CreateModel(
            name='Marriages',
            fields=[
                ('marr_id', models.AutoField(primary_key=True, serialize=False)),
                ('husband_id', models.ManyToManyField(null=True, related_name='husband', to='app.node')),
                ('wife_id', models.ManyToManyField(null=True, related_name='wife', to='app.node')),
            ],
        ),
    ]
