# Generated by Django 4.2.8 on 2023-12-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marriages',
            name='husband_id',
        ),
        migrations.AlterField(
            model_name='marriages',
            name='marr_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='marriages',
            name='wife_id',
        ),
        migrations.AddField(
            model_name='marriages',
            name='husband_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='husband', to='app.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marriages',
            name='wife_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wife', to='app.node'),
            preserve_default=False,
        ),
    ]
