# Generated by Django 4.2.8 on 2023-12-21 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usergallery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergallery',
            name='user',
        ),
        migrations.AddField(
            model_name='usergallery',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
