# Generated by Django 4.2.8 on 2023-12-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usergallery_user_usergallery_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergallery',
            old_name='user_id',
            new_name='user',
        ),
    ]
