# Generated by Django 4.2.8 on 2023-12-21 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_id_usergallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergallery',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
